version: 0.2

phases:
  build:
    commands:
      # build image
      - docker-compose build
      # log in to the public registry
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w3n0d9y7
      # push image
      - docker push public.ecr.aws/w3n0d9y7/hn:latest
      # clean up untagged images
      - sh ci/scripts/clean-ecr-images.sh hn
artifacts:
  files: "**/*"

