version: "3.1"
services:
  frontend:
    image: public.ecr.aws/w3n0d9y7/hn:latest
    container_name: hn-frontend
    build:
      context: static
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
